### ISSUE TITLE
Heroku app is down 

### ISSUE THREAD

**Issue by Kalebu** [HackEAC/mtaaAPI#3]
A request to Heroku results into Status: 503 Service Unavailable
probably something broke during deployment !!

**Comment by AnoRebel** [comment]
> A request to Heroku results into Status: 503 Service Unavailable
> probably something broke during deployment !!

Yes it did,check the comments in your PR. I'm looking for time to check it out.

**Comment by maotora** [comment]
Just made a `1 Char` PR to fix this issue. 😁

**Comment by AnoRebel** [comment]
> Just made a `1 Char` PR to fix this issue.

Cool, let me check.

**Comment by AnoRebel** [comment]
With the new PR's the error has changed to:

> AttributeError: 'Tanzania' object has no attribute 'name'

Will check it out again.

**Comment by AnoRebel** [comment]
Fixed this for now by commenting out the GraphQL url, until i get it working again.
