### ISSUE TITLE
Exceptional handling  should be added 

### ISSUE THREAD

**Issue by Kalebu** [HackEAC/mtaaAPI#5]
When someone tries to access a location that's is not there, 
the current implementation just throws 500 Internal Error 

We can add exception handling to handle this and returning empty [ ] or { } 
when exceptional is thrown

**Comment by AnoRebel** [comment]
I agree just been abit busy, but when I get the chance, there is alot of cleanup to do.

**Comment by AnoRebel** [comment]
I believe you already did that, much thanks.
