### ISSUE TITLE
Deploy the latest changes to heroku

### ISSUE THREAD

**Issue by Kalebu** [HackEAC/mtaaAPI#9]
https://mtaa-api.herokuapp.com/api/tanzania/Mbeya still raises internal server error

Can you please deploy the latest changes to heroku ?

**Comment by AnoRebel** [comment]
I did, as soon as I merged the changes, I deployed too. So that's probably a bug still in the code.

**Comment by Kalebu** [comment]
Guess I have it works on my machine issue (Let me have a look )

What might be causing this ?

**Comment by AnoRebel** [comment]
I'm not sure myself.
I'll take some time and check the whole thing out again.

**Comment by Kalebu** [comment]
Hi @AnoRebel, just tried it works just fine 

Thank you
